name: petbes
description: A social network for pet lovers.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  firebase_auth: ^3.3.0
  firebase_core: ^1.10.2
  firebase_messaging: ^10.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.5.0
  google_fonts: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.6
  faker: ^2.0.0
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^1.0.3
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  json_serializable: ^4.1.0
  logger: ^1.1.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher_icon/icon.png"
  image_path_android: "assets/launcher_icon/icon.png"
  adaptive_icon_background: "assets/launcher_icon/background.png"
  adaptive_icon_foreground: "assets/launcher_icon/foreground.png"

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

flutter_intl:
  enabled: true
  main_locale: es
  class_name: S